# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6de76ffff8c9abcbcd21893f68516f88f3323f91e7d03b2857235b728dcd2902092eeaf83656a397406b90051fa28a58418d604f0a7229da0642ce631a1e41ae

test:
  secret_key_base: 6a297e49081434db8e04a306c22e0ad176b7cec804396b834934dba6fe7c5915e539d5652f5bde231737ed031e29e423e59c20e79eba384079a00d63ad94a5a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
